version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/proshop
      JWT_SECRET: devsupersecret123
      PAYPAL_CLIENT_ID: dummy
      PAYPAL_APP_SECRET: dummy
      PAYPAL_API_URL: https://api-m.sandbox.paypal.com
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
